### ISSUE TITLE
FileNotFoundError with matches command

### ISSUE THREAD

**Issue by ioatzim** [delftdata/valentine#32]
Hello

I am trying to execute the following 2 lines of code but I get FileNotFoundError :

import valentine
matcher =valentine.algorithms.Coma(strategy="COMA_OPT")
matches = valentine_match(df1, df2, 'matcher'==matcher)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\grbus\prog\venv\lib\site-packages\valentine\__init__.py", line 20, in valentine_match
    matches = dict(sorted(matcher.get_matches(table_1, table_2).items(),
  File "C:\Users\grbus\prog\venv\lib\site-packages\valentine\algorithms\coma\coma.py", line 32, in get_matches
    self.__run_coma_jar(s_f_name, t_f_name, coma_output_file, tmp_folder_path)
  File "C:\Users\grbus\prog\venv\lib\site-packages\valentine\algorithms\coma\coma.py", line 49, in __run_coma_jar
    subprocess.call(['java', f'-Xmx{self.__java_XmX}',
  File "c:\users\grbus\appdata\local\programs\python\python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\grbus\appdata\local\programs\python\python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\grbus\appdata\local\programs\python\python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

How could this be resolved? Is it a windows issue or an issue with the valentine library itself?

**Comment by kPsarakis** [comment]
Hi @ioatzim, this is probably a Windows issue since we tested only with Ubuntu and macOS. 

We will look into it shortly and update the package.

**Comment by ioatzim** [comment]
Thank you for the quick responses. I will test with other methods and let you know

**Comment by ioatzim** [comment]
Hello

After installing as per your instructions, I get the following error:

>>> import valentine
>>> matcher =valentine.algorithms.Coma(strategy="COMA_OPT")
>>> matches = valentine.valentine_match(df1, df2, 'matcher'==matcher)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\grbus\prog\venv\lib\site-packages\valentine\__init__.py", line 23, in valentine_match
    raise NotAValentineMatcher('The method that you selected is not supported by Valentine')
valentine.NotAValentineMatcher: The method that you selected is not supported by Valentine
